using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ContinueTranslator.Core.IR;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace ContinueTranslator.Core.Emission;

internal sealed partial class CsEmitter
{
    // -------------------------------------------------------------------------
    // Cookie constants
    // -------------------------------------------------------------------------

    private const string CookieIgnore = "@ct:ignore";
    private const string CookieRenamePrefix = "@ct:rename=";
    private const string CookieTodo = "@ct:todo";

    // -------------------------------------------------------------------------
    // CollectResults — sorts results by RelativePath (deterministic output)
    // -------------------------------------------------------------------------

    partial void CollectResults(List<EmittedFile> results)
    {
        if (_needsSpreadMerge)
            results.Add(BuildSpreadMergeHelper());

        if (_needsHasPropertyHelper)
            results.Add(BuildHasPropertyHelper());

        results.Sort(static (a, b) =>
            StringComparer.OrdinalIgnoreCase.Compare(a.RelativePath, b.RelativePath));
    }

    /// <summary>
    /// Generates <c>SpreadMerge.cs</c>: a reflection-based utility that merges N objects
    /// left-to-right (last non-null value wins), matching TypeScript spread-object semantics.
    /// The file uses no NuGet dependencies and compiles on both net472 and net10.
    /// </summary>
    private static EmittedFile BuildSpreadMergeHelper()
    {
        const string source = """
            // <auto-generated/>
            // SpreadMerge — merges objects left-to-right (last non-null value wins).
            // Semantically equivalent to { ...a, ...b, ...c } in TypeScript.
            using System.Reflection;

            namespace ContinueCore;

            internal static class SpreadMerge
            {
                /// <summary>
                /// Creates a new instance of <typeparamref name="T"/> whose public settable
                /// properties are filled left-to-right from <paramref name="sources"/>;
                /// null sources are silently skipped; later values override earlier ones.
                /// </summary>
                internal static T Merge<T>(params object?[] sources) where T : new()
                {
                    T result = new();
                    PropertyInfo[] props = typeof(T).GetProperties(
                        BindingFlags.Public | BindingFlags.Instance);
                    foreach (object? src in sources)
                    {
                        if (src is null) continue;
                        foreach (PropertyInfo prop in props)
                        {
                            if (!prop.CanWrite) continue;
                            PropertyInfo? srcProp = src.GetType().GetProperty(prop.Name,
                                BindingFlags.Public | BindingFlags.Instance);
                            if (srcProp is null || !srcProp.CanRead) continue;
                            object? val = srcProp.GetValue(src);
                            if (val is not null)
                                prop.SetValue(result, val);
                        }
                    }
                    return result;
                }

                // Overload for when the concrete target type cannot be inferred —
                // returns a Dictionary<string, object?> instead.
                internal static Dictionary<string, object?> Merge(params object?[] sources)
                {
                    var result = new Dictionary<string, object?>(StringComparer.Ordinal);
                    foreach (object? src in sources)
                    {
                        if (src is null) continue;
                        foreach (PropertyInfo prop in src.GetType().GetProperties(
                            BindingFlags.Public | BindingFlags.Instance))
                        {
                            if (prop.CanRead)
                                result[prop.Name] = prop.GetValue(src);
                        }
                    }
                    return result;
                }
            }
            """;

        return new EmittedFile("SpreadMerge.cs", source);
    }

    /// <summary>
    /// Generates <c>HasProperty.cs</c>: a reflection-based utility that checks if an object
    /// has a public property with the given name, matching TypeScript's <c>in</c> operator semantics.
    /// The file uses no NuGet dependencies and compiles on both net472 and net10.
    /// </summary>
    private static EmittedFile BuildHasPropertyHelper()
    {
        const string source = """
            // <auto-generated/>
            // HasProperty — checks for property existence using reflection.
            // Semantically equivalent to ("prop" in obj) in TypeScript.
            using System.Reflection;

            namespace ContinueCore;

            internal static class HasPropertyHelper
            {
                /// <summary>
                /// Returns <see langword="true"/> if <paramref name="obj"/> is non-null and has a public
                /// instance property with the name <paramref name="propertyName"/>; otherwise <see langword="false"/>.
                /// </summary>
                internal static bool HasProperty(object? obj, string propertyName)
                {
                    ArgumentNullException.ThrowIfNull(propertyName);
                    if (obj is null)
                        return false;

                    return obj.GetType().GetProperty(
                        propertyName,
                        BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase) != null;
                }
            }
            """;

        return new EmittedFile("HasProperty.cs", source);
    }

    // -------------------------------------------------------------------------
    // Namespace / path helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Returns the longest common absolute directory prefix shared by all file paths
    /// in <paramref name="files"/>, or the directory of the first file when there is
    /// only one entry.
    /// </summary>
    internal static string ResolveCommonRoot(TsFile[] files)
    {
        if (files.Length == 0)
            return string.Empty;

        if (files.Length == 1)
            return Path.GetDirectoryName(files[0].FilePath) ?? string.Empty;

        string[] parts = files[0].FilePath.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        int commonLength = parts.Length;

        foreach (TsFile file in files.Skip(1))
        {
            string[] cur = file.FilePath.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            int shared = 0;
            while (shared < commonLength && shared < cur.Length &&
                   string.Equals(parts[shared], cur[shared], StringComparison.OrdinalIgnoreCase))
            {
                shared++;
            }
            commonLength = shared;
        }

        // commonLength is the number of path segments shared — rejoin without the final filename segment.
        // We want a directory, so use up to commonLength segments.
        return string.Join(Path.DirectorySeparatorChar.ToString(), parts.Take(commonLength));
    }

    /// <summary>
    /// Derives a dotted C# namespace from <paramref name="absoluteFilePath"/> relative to
    /// <paramref name="commonRoot"/>, prefixed with <c>ContinueCore</c>.
    /// Example: <c>/repo/core/protocol/types.ts</c> relative to <c>/repo/core</c>
    /// → <c>ContinueCore.Protocol</c>.
    /// </summary>
    internal static string DeriveNamespace(string absoluteFilePath, string commonRoot)
    {
        string rel = Path.GetRelativePath(commonRoot, Path.GetDirectoryName(absoluteFilePath) ?? string.Empty)
                         .Replace('\\', '/')
                         .Trim('/');

        if (rel == "." || rel == string.Empty)
            return "ContinueCore";

        // Strip leading "core/" segment if present (Continue's source lives under core/).
        if (rel.StartsWith("core/", StringComparison.OrdinalIgnoreCase))
            rel = rel["core/".Length..];

        if (rel == string.Empty)
            return "ContinueCore";

        IEnumerable<string> parts = rel.Split('/').Select(ToPascalCase);
        return "ContinueCore." + string.Join('.', parts);
    }

    /// <summary>
    /// Returns the relative output path (using forward slashes) for a file that belongs to
    /// <paramref name="ns"/> and whose base name is <paramref name="fileName"/>.
    /// Example: ns=<c>ContinueCore.Protocol</c>, fileName=<c>MyEnum.cs</c>
    /// → <c>Protocol/MyEnum.cs</c>.
    /// </summary>
    internal static string DeriveRelativePath(string ns, string fileName)
    {
        const string prefix = "ContinueCore";
        string sub = ns.StartsWith(prefix + ".", StringComparison.Ordinal)
            ? ns[(prefix.Length + 1)..].Replace('.', '/')
            : string.Empty;

        return sub.Length > 0 ? $"{sub}/{fileName}" : fileName;
    }

    // -------------------------------------------------------------------------
    // Cookie helpers
    // -------------------------------------------------------------------------

    internal static bool HasIgnoreCookie(string[] cookies) =>
        cookies.Any(static c => c.Equals(CookieIgnore, StringComparison.OrdinalIgnoreCase));

    internal static bool TryGetRenameCookie(string[] cookies, out string newName)
    {
        foreach (string cookie in cookies)
        {
            if (cookie.StartsWith(CookieRenamePrefix, StringComparison.OrdinalIgnoreCase))
            {
                newName = cookie[CookieRenamePrefix.Length..].Trim();
                return newName.Length > 0;
            }
        }
        newName = string.Empty;
        return false;
    }

    internal static bool HasTodoCookie(string[] cookies) =>
        cookies.Any(static c => c.StartsWith(CookieTodo, StringComparison.OrdinalIgnoreCase));

    // -------------------------------------------------------------------------
    // Trivia / comment helpers
    // -------------------------------------------------------------------------

    /// <summary>Wraps a node with a leading <c>// {text}</c> single-line comment trivia.</summary>
    internal static T WithLeadingLineComment<T>(T node, string text) where T : SyntaxNode
    {
        SyntaxTrivia comment = Comment($"// {text}");
        SyntaxTrivia eol = ElasticCarriageReturnLineFeed;
        return node.WithLeadingTrivia(node.GetLeadingTrivia().InsertRange(0, [comment, eol]));
    }

    // -------------------------------------------------------------------------
    // Statement-body helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Returns <see langword="true"/> when <paramref name="body"/> has no translatable statements,
    /// i.e. it is null or empty. Unknown statements are still emitted as raw text.
    /// </summary>
    private static bool IsBodyEmpty(TsStatement[]? body) =>
        body is null || body.Length == 0;

    // -------------------------------------------------------------------------
    // Type-name helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Converts a TypeScript identifier segment to PascalCase.
    /// E.g. <c>my-segment</c> → <c>MySegment</c>, <c>mySegment</c> → <c>MySegment</c>.
    /// </summary>
    internal static string ToPascalCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;

        // Split on hyphens and underscores, then capitalise each word.
        string[] words = s.Split(['-', '_'], StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(words.Select(w => char.ToUpperInvariant(w[0]) + w[1..]));
    }

    /// <summary>
    /// Converts TypeScript object literal type syntax (e.g., <c>{ prefix: string; suffix: string }</c>)
    /// into C# tuple syntax (e.g., <c>(string prefix, string suffix)</c>).
    /// Handles object literals at any nesting depth, including inside generic type arguments.
    /// Returns the original text if it cannot be converted.
    /// </summary>
    /// <remarks>
    /// Processes object literals recursively:
    /// 1. <c>{ prop: type; ... }</c> → <c>(type prop, ...)</c>
    /// 2. <c>Promise&lt;{ prop: type }&gt;</c> → <c>Task&lt;(type prop)&gt;</c>
    /// 3. <c>Map&lt;string, { prop: type }&gt;</c> → <c>Dictionary&lt;string, (type prop)&gt;</c>
    /// 
    /// Respects generic nesting (angle brackets) and converts all discovered object literals
    /// at every nesting level within the type expression.
    /// 
    /// Known limitations:
    /// - Union types: TypeScript union syntax (e.g., <c>{ a: string | number }</c>) is not converted.
    /// - Index signatures: Index signatures (e.g., <c>{ [key: string]: any }</c>) are not recognized.
    /// - Parsing failures: Falls back to 'object' if the final type cannot be parsed.
    /// </remarks>
    private static string ConvertObjectLiteralToTuple(string text) =>
        ConvertObjectLiteralsRecursive(text.Trim());

    /// <summary>
    /// Recursively scans the type text for object literal patterns at any nesting depth
    /// and converts each <c>{ prop: type; ... }</c> to tuple syntax <c>(type prop, ...)</c>.
    /// Returns the fully converted type string.
    /// </summary>
    private static string ConvertObjectLiteralsRecursive(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        StringBuilder result = new(text.Length);
        int i = 0;

        while (i < text.Length)
        {
            // Look for opening brace that could be an object literal
            if (text[i] == '{')
            {
                // Try to extract and convert the object literal
                if (TryExtractAndConvertObjectLiteral(text, i, out string? converted, out int endPos))
                {
                    // Successfully converted: append the tuple syntax and continue after the brace
                    result.Append(converted);
                    i = endPos + 1; // Skip past the closing brace
                    continue;
                }
            }

            // Not an object literal or couldn't convert: copy character as-is
            result.Append(text[i]);
            i++;
        }

        return result.ToString();
    }

    /// <summary>
    /// Attempts to extract and convert an object literal starting at position <paramref name="startPos"/>.
    /// Returns <see langword="true"/> if a valid object literal was found and converted.
    /// </summary>
    private static bool TryExtractAndConvertObjectLiteral(
        string text,
        int startPos,
        out string? converted,
        out int endPos)
    {
        converted = null;
        endPos = -1;

        // Find the matching closing brace, respecting nested structures
        int braceDepth = 0;
        int angleDepth = 0;
        int i = startPos;

        while (i < text.Length)
        {
            char ch = text[i];

            if (ch == '{')
                braceDepth++;
            else if (ch == '}')
            {
                braceDepth--;
                if (braceDepth == 0)
                {
                    // Found the matching closing brace
                    endPos = i;
                    string objectLiteralContent = text[(startPos + 1)..i].Trim();

                    // Attempt to parse as object literal
                    if (TryConvertObjectLiteralContent(objectLiteralContent, out string? tuple))
                    {
                        converted = tuple;
                        return true;
                    }
                    return false;
                }
            }
            else if (ch == '<' && braceDepth == 1)
            {
                angleDepth++;
            }
            else if (ch == '>' && braceDepth == 1)
            {
                angleDepth--;
            }

            i++;
        }

        return false;
    }

    /// <summary>
    /// Converts the content of an object literal (text between braces) to tuple syntax.
    /// </summary>
    private static bool TryConvertObjectLiteralContent(string content, out string? tuple)
    {
        tuple = null;

        if (content.Length == 0)
            return false; // Empty object literal

        // Split on semicolons, respecting generic nesting
        List<string> properties = SplitPropertiesRespectingGenerics(content);

        if (properties.Count == 0)
            return false;

        // Parse each property as "name: type" and build tuple elements
        List<string> tupleElements = new();
        foreach (string prop in properties)
        {
            string trimmedProp = prop.Trim();
            if (trimmedProp.Length == 0)
                continue;

            // Split on the first ':' to separate name and type
            int colonIdx = trimmedProp.IndexOf(':');
            if (colonIdx <= 0)
                return false; // Invalid property syntax

            string name = trimmedProp[..colonIdx].Trim();
            string type = trimmedProp[(colonIdx + 1)..].Trim();

            // Validate: name should be a valid identifier
            if (!IsValidIdentifier(name) || type.Length == 0)
                return false;

            // Recursively convert any nested object literals in the type
            type = ConvertObjectLiteralsRecursive(type);

            // Build tuple element: "type name"
            tupleElements.Add($"{type} {name}");
        }

        if (tupleElements.Count == 0)
            return false;

        // Return the C# tuple syntax
        tuple = $"({string.Join(", ", tupleElements)})";
        return true;
    }

    /// <summary>
    /// Splits a property list string on semicolons while respecting nested generic angle brackets.
    /// Example: <c>a: string; b: List&lt;int&gt;; c: bool</c> → three properties.
    /// </summary>
    private static List<string> SplitPropertiesRespectingGenerics(string text)
    {
        List<string> parts = [];
        int depth = 0;
        int start = 0;

        for (int i = 0; i < text.Length; i++)
        {
            char ch = text[i];
            if (ch == '<')
                depth++;
            else if (ch == '>')
                depth--;
            else if (ch == ';' && depth == 0)
            {
                parts.Add(text[start..i]);
                start = i + 1;
            }
        }

        // Add the final segment (may not end with ';')
        if (start < text.Length)
            parts.Add(text[start..]);

        return parts;
    }

    /// <summary>
    /// Returns <see langword="true"/> if <paramref name="name"/> is a valid C# identifier.
    /// </summary>
    private static bool IsValidIdentifier(string name)
    {
        if (name.Length == 0)
            return false;

        // First character must be letter or underscore
        char first = name[0];
        if (!char.IsLetter(first) && first != '_')
            return false;

        // Remaining characters must be letter, digit, or underscore
        for (int i = 1; i < name.Length; i++)
        {
            char ch = name[i];
            if (!char.IsLetterOrDigit(ch) && ch != '_')
                return false;
        }

        return true;
    }

    /// <summary>
    /// Converts a raw type-text string into a <see cref="TypeSyntax"/> the compiler accepts.
    /// Defaults to <c>object</c> when the text is empty or unparseable.
    /// </summary>
    internal static TypeSyntax ParseTypeSyntax(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return PredefinedType(Token(SyntaxKind.ObjectKeyword));

        if (text == "Task<void>") text = "Task";

        // TypeScript `any` and `unknown` have no C# equivalent; map to object.
        if (text is "any" or "unknown") return PredefinedType(Token(SyntaxKind.ObjectKeyword));
        if (text is "any?" or "unknown?") return NullableType(PredefinedType(Token(SyntaxKind.ObjectKeyword)));

        // Convert TypeScript object literal types to C# tuple syntax before parsing
        text = ConvertObjectLiteralToTuple(text);

        try
        {
            return (TypeSyntax)SyntaxFactory.ParseTypeName(text);
        }
        catch
        {
            return PredefinedType(Token(SyntaxKind.ObjectKeyword));
        }
    }

    // -------------------------------------------------------------------------
    // Compilation-unit builder
    // -------------------------------------------------------------------------

    /// <summary>
    /// Wraps <paramref name="members"/> in a file-scoped namespace declaration and returns
    /// the normalised source text with post-processing to improve formatting of anonymous object literals.
    /// </summary>
    internal static string BuildCompilationUnit(string ns, IEnumerable<MemberDeclarationSyntax> members)
    {
        FileScopedNamespaceDeclarationSyntax nsDecl =
            FileScopedNamespaceDeclaration(ParseName(ns))
                .WithMembers(List(members))
                .NormalizeWhitespace();

        CompilationUnitSyntax cu = CompilationUnit()
            .WithMembers(SingletonList<MemberDeclarationSyntax>(nsDecl))
            .NormalizeWhitespace();

        string result = cu.ToFullString();

        // Post-process to fix formatting issues with anonymous object literals:
        // - Remove spaces before commas in object initializers ( , → ,)
        // - Collapse excessive newlines in nested object initializers into single lines
        result = FixAnonymousObjectFormatting(result);

        return result;
    }

    /// <summary>
    /// Post-processes generated C# code to improve formatting of anonymous object literals.
    /// Fixes issues like:
    /// - Spaces before commas: "value , " → "value,"
    /// - Excessive line breaks in nested objects
    /// - Missing 'new' keyword in nested anonymous object creations
    /// </summary>
     private static string FixAnonymousObjectFormatting(string code)
    {
        // Fix spaces before commas and closing braces in object initializers
        // Pattern: any whitespace (including newlines) followed by a comma
        code = System.Text.RegularExpressions.Regex.Replace(code, @"\s+,", ",");

        // Fix spaces before closing braces in object initializers
        // Pattern: any whitespace (including newlines) followed by }
        code = System.Text.RegularExpressions.Regex.Replace(code, @"\s+}", "}");

        // Collapse multiple blank lines into single blank lines
        code = System.Text.RegularExpressions.Regex.Replace(code, @"\n\s*\n\s*\n", "\n\n");

        // Convert colons to equals in anonymous object member syntax.
        // This handles the case where EmitObjectLiteral's NameEquals() doesn't produce equals signs
        // (likely due to Roslyn normalization or other post-processing).
        // 
        // Pattern: Match "identifier:" (with optional whitespace) but ONLY when:
        // - The identifier is preceded by whitespace/newline (inside a block, not after operators)
        // - The identifier is NOT part of a ternary expression (where ':' comes after '?')
        // 
        // The regex uses:
        // - (?<!\?)  : Negative lookbehind to avoid matching ternary operator colons after '?'
        // - \b       : Word boundary to match identifier boundaries  
        // - (\w+)    : Capture the identifier name
        // - \s*:     : Optional whitespace followed by colon
        // 
        // Since ternary operators have the pattern "expr ? true : false", and we're in an
        // object literal context with identifiers at line start or after commas, the negative
        // lookbehind for '?' correctly avoids ternary colons while matching object colons.
        code = System.Text.RegularExpressions.Regex.Replace(
            code,
            @"(?<!\?)\b(\w+)\s*:\s*",
            "$1 = ",
            System.Text.RegularExpressions.RegexOptions.Multiline);

        // Fix: Inject 'new' keyword before opening braces in property assignments that are missing it.
        // This handles nested anonymous objects: "propertyName = {" → "propertyName = new {"
        // We match "= " followed by optional whitespace and "{", but NOT if preceded by "new"
        // RegexOptions.Multiline allows \s* to match newlines between = and {
        code = System.Text.RegularExpressions.Regex.Replace(
            code,
            @"(?<!new\s)=\s*\{",
            "= new {",
            System.Text.RegularExpressions.RegexOptions.Multiline);

        // Collapse redundant line breaks around single-line properties
        // E.g., "line = \n node.startPosition.row," -> "line = node.startPosition.row,"
        code = System.Text.RegularExpressions.Regex.Replace(
            code,
            @"(\s*=\s*)\n\s+([^\n{}\[\]]+,)",
            "$1 $2");

        return code;
    }

    // -------------------------------------------------------------------------
    // Generator method name helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Converts a camelCase variable name to PascalCase method name.
    /// Example: "generatorWithCancellation" → "GeneratorWithCancellation"
    /// </summary>
    private static string VariableNameToMethodName(string? varName)
    {
        if (string.IsNullOrEmpty(varName))
            return "__GeneratorFunc";

        // Capitalize the first character
        return char.ToUpperInvariant(varName[0]) + varName[1..];
    }
}
