using System;
using ContinueVS.Core.Types;
using Newtonsoft.Json;

namespace ContinueVS.Core.Types
{
    /// <summary>
    /// Represents a single attempt in the change execution retry loop.
    /// Tracks the change applied, whether it was refined, and its outcome.
    /// </summary>
    public class ChangeExecutionAttempt
    {
        /// <summary>
        /// Sequence number of this attempt (1 for original, 2+ for retries).
        /// </summary>
        [JsonProperty("attemptNumber")]
        public int AttemptNumber { get; set; }

        /// <summary>
        /// The CodeChange that was executed in this attempt.
        /// </summary>
        [JsonProperty("executedChange")]
        public CodeChange? ExecutedChange { get; set; }

        /// <summary>
        /// True if this change was generated by FailureAnalyzerService as a refinement;
        /// False if this is the original change from the phase definition.
        /// </summary>
        [JsonProperty("isRefinedAttempt")]
        public bool IsRefinedAttempt { get; set; }

        /// <summary>
        /// Description of refinement reasoning (e.g., "Based on null reference analysis, added null check at line 42").
        /// Null if this is the original, non-refined attempt.
        /// </summary>
        [JsonProperty("refinementDetails")]
        public string? RefinementDetails { get; set; }

        /// <summary>
        /// Timestamp when this attempt was executed.
        /// </summary>
        [JsonProperty("executedAt")]
        public DateTime ExecutedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Whether this attempt succeeded (true) or failed (false).
        /// </summary>
        [JsonProperty("succeeded")]
        public bool Succeeded { get; set; }

        /// <summary>
        /// Error message if attempt failed; null if succeeded.
        /// </summary>
        [JsonProperty("errorMessage")]
        public string? ErrorMessage { get; set; }

        /// <summary>
        /// Determines if this attempt was successful.
        /// </summary>
        public bool IsSuccessful() => Succeeded;
    }
}
