using System;
using System.Collections.Generic;
using System.Linq;

namespace ContinueVS.Core.Types
{
    /// <summary>
    /// Represents a complete instrumentation strategy generated by the LLM.
    /// Immutable after creation; used to drive source modifications via ChangeStack.
    /// </summary>
    public class InstrumentationStrategy
    {
        /// <summary>
        /// Unique identifier for this strategy.
        /// </summary>
        public string StrategyId { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// Human-readable description of the instrumentation strategy.
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// The type of instrumentation being applied.
        /// </summary>
        public InstrumentationType InstrumentationType { get; set; }

        /// <summary>
        /// The target file to instrument (relative or absolute path).
        /// </summary>
        public string TargetFile { get; set; } = string.Empty;

        /// <summary>
        /// Collection of code snippets to insert.
        /// </summary>
        public List<InstrumentationSnippet> CodeSnippets { get; set; } = new List<InstrumentationSnippet>();

        /// <summary>
        /// LLM reasoning: why was this instrumentation chosen?
        /// </summary>
        public string Rationale { get; set; } = string.Empty;

        /// <summary>
        /// UTC timestamp when the strategy was created.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Validates the strategy has required fields.
        /// </summary>
        /// <returns>True if valid; false otherwise.</returns>
        public bool IsValid()
        {
            return !string.IsNullOrWhiteSpace(TargetFile)
                && CodeSnippets.Any()
                && CodeSnippets.All(s => !string.IsNullOrWhiteSpace(s.Code));
        }
    }
}
