using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace ContinueVS.Core.Types
{
    /// <summary>
    /// Represents an LLM-generated refinement attempt for a failed change.
    /// Contains error analysis, generated hypotheses, a refined/retryable change, and confidence metrics.
    /// </summary>
    public class RefinementAttempt
    {
        /// <summary>
        /// The original error that triggered this refinement attempt.
        /// </summary>
        [JsonProperty("originalError")]
        public ErrorAnalysisResult? OriginalError { get; set; }

        /// <summary>
        /// List of hypotheses generated by LLM about root causes of the error.
        /// Ordered by plausibility or generated sequence.
        /// </summary>
        [JsonProperty("hypotheses")]
        public List<string> Hypotheses { get; set; } = new List<string>();

        /// <summary>
        /// The refined CodeChange to attempt next (may be identical to previous or substantially altered).
        /// Null if no viable refinement was generated.
        /// </summary>
        [JsonProperty("refinedChange")]
        public CodeChange? RefinedChange { get; set; }

        /// <summary>
        /// Confidence score (0.0 to 1.0) for this refinement's likelihood of success.
        /// Based on error clarity, hypothesis quality, and pattern matching.
        /// </summary>
        [JsonProperty("confidenceScore")]
        public double ConfidenceScore { get; set; }

        /// <summary>
        /// Textual description of the refinement approach taken by the LLM.
        /// Explains reasoning for the refined change.
        /// </summary>
        [JsonProperty("approachDescription")]
        public string? ApproachDescription { get; set; }

        /// <summary>
        /// Count of refinement attempts made on this error before generating this RefinementAttempt.
        /// Used to track retry progression.
        /// </summary>
        [JsonProperty("attemptNumber")]
        public int AttemptNumber { get; set; }

        /// <summary>
        /// Timestamp when this refinement was generated.
        /// </summary>
        [JsonProperty("generatedAt")]
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

        public RefinementAttempt()
        {
        }

        public RefinementAttempt(ErrorAnalysisResult originalError, int attemptNumber = 1)
        {
            OriginalError = originalError ?? throw new ArgumentNullException(nameof(originalError));
            AttemptNumber = attemptNumber;
            ConfidenceScore = 0.0;
        }

        /// <summary>
        /// Determines if this refinement attempt is viable (has a refined change and confidence above threshold).
        /// </summary>
        public bool IsViable(double confidenceThreshold = 0.3)
        {
            return RefinedChange != null && ConfidenceScore >= confidenceThreshold;
        }
    }
}
