/**
 * npm Package Integrity Validation Utility
 *
 * Provides programmatic validation of npm package integrity through:
 * - SHA256 checksum verification
 * - manifest.json metadata validation
 *
 * This module is ESM (ES Modules) and uses only Node.js built-ins.
 * No external npm dependencies.
 *
 * @module src/versions/v2.0.0/lib/integrity.js
 * @version 1.0.0
 * @author Bridge Architecture Team
 *
 * Related Steps: 11 (cache download), 12 (startup validation), 37 (checksum generation)
 */

import fs from 'fs/promises';
import path from 'path';
import crypto from 'crypto';

// -------------------------------------------------------
// Custom Error Types
// -------------------------------------------------------

/**
 * Base error class for integrity validation failures.
 * @class IntegrityError
 * @extends Error
 */
class IntegrityError extends Error {
  constructor(message) {
    super(message);
    this.name = 'IntegrityError';
  }
}

/**
 * Error class for checksum validation failures.
 * @class ChecksumError
 * @extends IntegrityError
 */
class ChecksumError extends IntegrityError {
  constructor(message, expected, computed) {
    super(message);
    this.name = 'ChecksumError';
    this.expected = expected;
    this.computed = computed;
  }
}

/**
 * Error class for manifest validation failures.
 * @class ManifestError
 * @extends IntegrityError
 */
class ManifestError extends IntegrityError {
  constructor(message) {
    super(message);
    this.name = 'ManifestError';
  }
}

// -------------------------------------------------------
// Helper Functions
// -------------------------------------------------------

/**
 * Compute SHA256 hash of a file.
 *
 * @param {string} filePath - Absolute or relative path to the file
 * @returns {Promise<string>} SHA256 hash in lowercase hex format (64 characters)
 * @throws {IntegrityError} If file cannot be read
 *
 * @example
 * const hash = await computeSHA256('/path/to/package.tgz');
 * console.log(hash); // 'abc123def456...'
 */
async function computeSHA256(filePath) {
  try {
    const fileBuffer = await fs.readFile(filePath);
    const hash = crypto.createHash('sha256').update(fileBuffer).digest('hex');
    return hash.toLowerCase();
  } catch (error) {
    throw new IntegrityError(
      `Failed to compute SHA256 for ${filePath}: ${error.message}`
    );
  }
}

/**
 * Validate checksum format (64 lowercase hex characters).
 *
 * @param {string} hash - The hash string to validate
 * @returns {boolean} True if valid, false otherwise
 *
 * @example
 * validateChecksumFormat('abc123def456...'); // true (if exactly 64 hex chars)
 * validateChecksumFormat('ABC123'); // false (invalid format)
 */
function validateChecksumFormat(hash) {
  if (typeof hash !== 'string') return false;
  const normalizedHash = hash.toLowerCase();
  return /^[a-f0-9]{64}$/.test(normalizedHash);
}

/**
 * Parse checksum file in format: "{hash}  {filename}"
 *
 * Checksum files are typically generated by:
 * - `sha256sum` tool (Unix): "abc123... filename"
 * - PowerShell `Get-FileHash`: "ABC123... filename"
 * - This utility (Step 37)
 *
 * Format is flexible (1+ spaces between hash and filename).
 *
 * @param {string} checksumFilePath - Path to the .tgz.sha256 file
 * @returns {Promise<Object>} { hash: string, filename: string }
 * @throws {IntegrityError} If file cannot be read or format is invalid
 *
 * @example
 * const checksum = await parseChecksumFile('.cache/npm-packages/v2.0.0/continue-v2.0.0.tgz.sha256');
 * // { hash: 'abc123...', filename: 'continue-v2.0.0.tgz' }
 */
async function parseChecksumFile(checksumFilePath) {
  try {
    const content = await fs.readFile(checksumFilePath, 'utf-8');
    const line = content.trim().split('\n')[0]; // First line only

    if (!line) {
      throw new IntegrityError(`Checksum file is empty: ${checksumFilePath}`);
    }

    // Split on whitespace (1+ spaces or tabs)
    const parts = line.split(/\s+/);
    if (parts.length < 2) {
      throw new IntegrityError(
        `Invalid checksum file format. Expected: "hash  filename", got: "${line}"`
      );
    }

    const hash = parts[0].toLowerCase();
    const filename = parts[1];

    if (!validateChecksumFormat(hash)) {
      throw new IntegrityError(
        `Invalid checksum format: "${hash}". Expected 64 lowercase hex characters.`
      );
    }

    return { hash, filename };
  } catch (error) {
    if (error instanceof IntegrityError) {
      throw error;
    }
    throw new IntegrityError(
      `Failed to read checksum file ${checksumFilePath}: ${error.message}`
    );
  }
}

/**
 * Load and validate JSON manifest structure.
 *
 * Required fields: version, continueVersion, releaseDate, status, checksums
 *
 * @param {string} manifestPath - Path to manifest.json
 * @returns {Promise<Object>} Parsed manifest object
 * @throws {ManifestError} If file missing, invalid JSON, or missing required fields
 *
 * @example
 * const manifest = await loadManifest('.cache/npm-packages/v2.0.0/manifest.json');
 * console.log(manifest.version); // '2.0.0'
 */
async function loadManifest(manifestPath) {
  try {
    const content = await fs.readFile(manifestPath, 'utf-8');
    const manifest = JSON.parse(content);
    return manifest;
  } catch (error) {
    if (error instanceof SyntaxError) {
      throw new ManifestError(
        `Invalid JSON in manifest: ${manifestPath}: ${error.message}`
      );
    }
    throw new ManifestError(
      `Failed to read manifest ${manifestPath}: ${error.message}`
    );
  }
}

/**
 * Validate manifest has all required fields.
 *
 * Required fields:
 * - version: Semantic version (e.g., '2.0.0')
 * - continueVersion: Continue package version (e.g., '0.4.x')
 * - releaseDate: ISO 8601 timestamp
 * - status: 'stable', 'tested', 'beta', etc.
 * - checksums: Object with 'sha256' field
 *
 * @param {Object} manifest - Parsed manifest object
 * @param {string} expectedVersion - Expected version (e.g., '2.0.0' or 'v2.0.0')
 * @throws {ManifestError} If required fields missing or version mismatch
 *
 * @example
 * validateManifestStructure(manifest, '2.0.0');
 */
function validateManifestStructure(manifest, expectedVersion) {
  const requiredFields = ['version', 'continueVersion', 'releaseDate', 'status', 'checksums'];

  // Check for required fields
  for (const field of requiredFields) {
    if (!(field in manifest) || manifest[field] === null || manifest[field] === undefined) {
      throw new ManifestError(
        `Manifest missing required field: "${field}"`
      );
    }
  }

  // Normalize versions for comparison (remove leading 'v')
  const manifestVersion = manifest.version.toString().replace(/^v/, '');
  const expectedVer = expectedVersion.toString().replace(/^v/, '');

  if (manifestVersion !== expectedVer) {
    throw new ManifestError(
      `Version mismatch. Expected: "${expectedVer}", got: "${manifestVersion}"`
    );
  }

  // Validate checksums object
  if (!manifest.checksums || typeof manifest.checksums !== 'object') {
    throw new ManifestError(`Manifest "checksums" must be an object`);
  }

  if (!('sha256' in manifest.checksums)) {
    throw new ManifestError(`Manifest checksums must include "sha256" field`);
  }
}

// -------------------------------------------------------
// Main Validation Functions (Exported)
// -------------------------------------------------------

/**
 * Validate SHA256 checksum of an npm package file.
 *
 * Reads expected checksum from {packagePath}.sha256 file and compares
 * it to the computed SHA256 hash of the package file.
 *
 * @param {string} packagePath - Absolute path to .tgz file (e.g., 'continue-v2.0.0.tgz')
 * @param {string} checksumPath - Absolute path to .sha256 file (e.g., 'continue-v2.0.0.tgz.sha256')
 * @returns {Promise<Object>} Validation result:
 *   {
 *     valid: boolean,
 *     packagePath: string,
 *     checksumPath: string,
 *     computedHash: string,
 *     expectedHash: string,
 *     error: string | null
 *   }
 *
 * @example
 * const result = await validatePackageChecksum(
 *   'E:\\cache\\continue-v2.0.0.tgz',
 *   'E:\\cache\\continue-v2.0.0.tgz.sha256'
 * );
 *
 * if (result.valid) {
 *   console.log('✅ Package integrity verified');
 * } else {
 *   console.error(`❌ ${result.error}`);
 * }
 */
async function validatePackageChecksum(packagePath, checksumPath) {
  const result = {
    valid: false,
    packagePath,
    checksumPath,
    computedHash: '',
    expectedHash: '',
    error: null
  };

  try {
    // Step 1: Parse checksum file
    const { hash: expectedHash } = await parseChecksumFile(checksumPath);
    result.expectedHash = expectedHash;

    // Step 2: Compute actual hash
    const computedHash = await computeSHA256(packagePath);
    result.computedHash = computedHash;

    // Step 3: Compare hashes
    if (computedHash !== expectedHash) {
      result.error = (
        `Checksum mismatch. ` +
        `Expected: ${expectedHash}, ` +
        `Computed: ${computedHash}`
      );
      return result;
    }

    result.valid = true;
    return result;
  } catch (error) {
    result.error = error instanceof IntegrityError
      ? error.message
      : `Unexpected error: ${error.message}`;
    return result;
  }
}

/**
 * Validate manifest.json file for a package version.
 *
 * Checks:
 * - File exists and is valid JSON
 * - Required fields present: version, continueVersion, releaseDate, status, checksums
 * - Version matches expected value
 * - Checksums object contains 'sha256'
 *
 * @param {string} manifestPath - Absolute path to manifest.json
 * @param {string} expectedVersion - Expected version (e.g., '2.0.0' or 'v2.0.0')
 * @returns {Promise<Object>} Validation result:
 *   {
 *     valid: boolean,
 *     manifestPath: string,
 *     version: string | null,
 *     continueVersion: string | null,
 *     metadata: Object | null,
 *     error: string | null
 *   }
 *
 * @example
 * const result = await validateManifest(
 *   'E:\\cache\\manifest.json',
 *   '2.0.0'
 * );
 *
 * if (result.valid) {
 *   console.log(`✅ Manifest valid: Continue ${result.continueVersion}`);
 * } else {
 *   console.error(`❌ ${result.error}`);
 * }
 */
export async function validateManifest(manifestPath, expectedVersion) {
  const result = {
    valid: false,
    manifestPath,
    version: null,
    continueVersion: null,
    metadata: null,
    error: null
  };

  try {
    // Step 1: Load manifest
    const manifest = await loadManifest(manifestPath);
    result.version = manifest.version;
    result.continueVersion = manifest.continueVersion;

    // Step 2: Validate structure
    validateManifestStructure(manifest, expectedVersion);

    // Step 3: Store metadata
    result.metadata = {
      version: manifest.version,
      continueVersion: manifest.continueVersion,
      releaseDate: manifest.releaseDate,
      status: manifest.status,
      checksums: manifest.checksums
    };

    result.valid = true;
    return result;
  } catch (error) {
    result.error = error instanceof ManifestError
      ? error.message
      : `Unexpected error: ${error.message}`;
    return result;
  }
}

/**
 * Validate complete package integrity (checksum + manifest).
 *
 * This is the orchestrator function that combines checksum and manifest validation.
 * Both validations must pass for the result to be valid.
 *
 * Directory structure expected:
 * ```
 * versionDir/
 * ├── continue-{version}.tgz
 * ├── continue-{version}.tgz.sha256
 * └── manifest-{version}.json (or manifest.json)
 * ```
 *
 * @param {string} versionDir - Absolute path to version directory (e.g., '.cache/npm-packages/v2.0.0')
 * @param {string} version - Version string (e.g., '2.0.0' or 'v2.0.0')
 * @returns {Promise<Object>} Comprehensive validation result:
 *   {
 *     valid: boolean,
 *     version: string,
 *     versionDir: string,
 *     packagePath: string,
 *     manifestPath: string,
 *     checksumValid: boolean,
 *     manifestValid: boolean,
 *     metadata: {
 *       continueVersion: string,
 *       releaseDate: string,
 *       status: string
 *     },
 *     errors: string[]
 *   }
 *
 * @example
 * const result = await validatePackageIntegrity(
 *   'E:\\GitRepos\\ContinueVS\\.cache\\npm-packages\\v2.0.0',
 *   '2.0.0'
 * );
 *
 * if (result.valid) {
 *   console.log('✅ Package ready for launch');
 *   console.log(`   Continue: ${result.metadata.continueVersion}`);
 * } else {
 *   console.error('❌ Validation failed:');
 *   result.errors.forEach(err => console.error(`   - ${err}`));
 * }
 */
async function validatePackageIntegrity(versionDir, version) {
  // Normalize version (remove leading 'v')
  const versionNum = version.toString().replace(/^v/, '');
  const versionTag = version.toString().startsWith('v') ? version : `v${version}`;

  const result = {
    valid: false,
    version: versionNum,
    versionDir,
    packagePath: '',
    manifestPath: '',
    checksumValid: false,
    manifestValid: false,
    metadata: null,
    errors: []
  };

  // Construct file paths
  const packageName = `continue-${versionTag}.tgz`;
  const checksumName = `${packageName}.sha256`;
  const manifestName = `manifest-${versionTag}.json`;

  const packagePath = path.join(versionDir, packageName);
  const checksumPath = path.join(versionDir, checksumName);
  const manifestPath = path.join(versionDir, manifestName);

  result.packagePath = packagePath;
  result.manifestPath = manifestPath;

  // Validate checksum
  const checksumResult = await validatePackageChecksum(packagePath, checksumPath);
  result.checksumValid = checksumResult.valid;
  if (!checksumResult.valid) {
    result.errors.push(checksumResult.error);
  }

  // Validate manifest
  const manifestResult = await validateManifest(manifestPath, versionNum);
  result.manifestValid = manifestResult.valid;
  if (!manifestResult.valid) {
    result.errors.push(manifestResult.error);
  } else {
    result.metadata = manifestResult.metadata;
  }

  // Overall validity: both checks must pass
  result.valid = result.checksumValid && result.manifestValid;

  return result;
}

// -------------------------------------------------------
// Exports (for test and external access)
// -------------------------------------------------------

export {
  computeSHA256,
  validateChecksumFormat,
  parseChecksumFile,
  validateManifestStructure,
  validatePackageChecksum,
  validatePackageIntegrity,
  IntegrityError,
  ChecksumError,
  ManifestError
};
