#!/usr/bin/env node
import assert from 'assert';
import { describe, it } from 'mocha';
import { createGoToDefinitionHandler } from '../lib/go-to-definition-handler.mjs';

describe('GoToDefinition Handler Step68', () => {
  it('resolves symbol', async () => { const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'1',data:{filepath:'F.cs',line:0,column:0}}; const r = await h(m,{symbolExtractor:ext}); assert(typeof r.success === 'boolean'); });
  it('rejects invalid line', async () => { const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'2',data:{filepath:'F.cs',line:-1,column:0}}; const r = await h(m,{symbolExtractor:ext}); assert.strictEqual(r.success,false); });
  it('rejects invalid column', async () => { const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'3',data:{filepath:'F.cs',line:0,column:-1}}; const r = await h(m,{symbolExtractor:ext}); assert.strictEqual(r.success,false); });
  it('rejects missing filepath', async () => { const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'4',data:{line:0,column:0}}; const r = await h(m,{symbolExtractor:ext}); assert.strictEqual(r.success,false); });
  it('handles project scope', async () => { const dp = {getAllDocuments:()=>[],getDocument:()=>null}; const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext,documentProvider:dp}); const m = {messageType:'bridge:goToDefinition',messageId:'5',data:{filepath:'F.cs',line:0,column:0,searchScope:'project'}}; const r = await h(m,{symbolExtractor:ext,documentProvider:dp}); assert.strictEqual(r.success,true); });
  it('handles file scope', async () => { const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'6',data:{filepath:'F.cs',line:0,column:0,searchScope:'file'}}; const r = await h(m,{symbolExtractor:ext}); assert.strictEqual(r.success,true); });
  it('returns valid data', async () => { const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'7',data:{filepath:'F.cs',line:0,column:0}}; const r = await h(m,{symbolExtractor:ext}); assert(r.data || r.error); });
  it('handles extractor failure', async () => { const ext = {extractSymbols:async()=>{throw new Error('fail');}}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'8',data:{filepath:'F.cs',line:0,column:0}}; const r = await h(m,{symbolExtractor:ext}); assert.strictEqual(r.success,false); });
  it('with logger context', async () => { const ext = {extractSymbols:async()=>[]}; const log = {debug:()=>{},info:()=>{},warn:()=>{},error:()=>{}}; const h = createGoToDefinitionHandler({symbolExtractor:ext,logger:log}); const m = {messageType:'bridge:goToDefinition',messageId:'9',data:{filepath:'F.cs',line:0,column:0}}; const r = await h(m,{symbolExtractor:ext,logger:log}); assert(typeof r.success === 'boolean'); });
  it('with metrics context', async () => { const ext = {extractSymbols:async()=>[]}; const met = {record:()=>{}}; const h = createGoToDefinitionHandler({symbolExtractor:ext,metrics:met}); const m = {messageType:'bridge:goToDefinition',messageId:'10',data:{filepath:'F.cs',line:0,column:0}}; const r = await h(m,{symbolExtractor:ext,metrics:met}); assert(typeof r.success === 'boolean'); });
  it('null symbol table handling', async () => { const ext = {extractSymbols:async()=>null}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'11',data:{filepath:'F.cs',line:0,column:0}}; const r = await h(m,{symbolExtractor:ext}); assert(typeof r.success === 'boolean'); });
  it('workspace scope search', async () => { const dp = {getAllDocuments:()=>[],getDocument:()=>null}; const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext,documentProvider:dp}); const m = {messageType:'bridge:goToDefinition',messageId:'12',data:{filepath:'F.cs',line:0,column:0,searchScope:'workspace'}}; const r = await h(m,{symbolExtractor:ext,documentProvider:dp}); assert.strictEqual(r.success,true); });
  it('empty data handling', async () => { const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'13',data:{filepath:'F.cs',line:0,column:0}}; const r = await h(m,{symbolExtractor:ext}); assert(r.hasOwnProperty('success')); });
  it('response structure valid', async () => { const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'14',data:{filepath:'F.cs',line:0,column:0}}; const r = await h(m,{symbolExtractor:ext}); assert(r.success===true || r.success===false); });
  it('handles valid request', async () => { const ext = {extractSymbols:async()=>[]}; const h = createGoToDefinitionHandler({symbolExtractor:ext}); const m = {messageType:'bridge:goToDefinition',messageId:'15',data:{filepath:'Test.cs',line:0,column:0}}; const r = await h(m,{symbolExtractor:ext}); assert.strictEqual(typeof r.success,'boolean'); });
});
